/* CIL Browser (https://github.com/MSDN-WhiteKnight/CilBrowser)
 * Copyright (c) 2023,  MSDN.WhiteKnight 
 * License: BSD 3-Clause */
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using CilBrowser.Core;
using CilBrowser.Core.Structure;

namespace CilBrowser.Tests.Structure
{
    [TestClass]
    public class AssemblySectionNodeTests
    {
        [TestMethod]
        public void Test_Render()
        {
            // Build node
            Assembly ass = typeof(HtmlGenerator).Assembly;
            string assemblyVersion = ass.GetName().Version.ToString(4);
            string productVersion = ass.GetName().Version.ToString(3);
            Dictionary<string, List<Type>> typeMap = new Dictionary<string, List<Type>>();
            AssemblySectionNode node = new AssemblySectionNode(ass, typeMap);
            AssemblyManifestNode manifest = new AssemblyManifestNode(ass);
            node.AddPage(manifest);
            NamespaceNode ns = new NamespaceNode("CilBrowser.Core", "CilBrowser.Core");
            ns.AddPage(new TypeNode(typeof(HtmlGenerator), typeMap));
            node.AddSection(ns);

            // Render node
            HtmlGenerator generator = new HtmlGenerator(ass);
            string html = node.RenderToString(generator, new CilBrowserOptions());

            // Verify output
            string expected = @"<html><head><title>.NET CIL Browser - CilBrowser.Core</title><style>.memberid { color: rgb(43, 145, 175); text-decoration: none; }</style></head>
<body><p>.NET CIL Browser</p><h1>CilBrowser.Core</h1><table cellpadding=""4""><tr><td>Assembly version</td><td>%ASSEMBLY_VERSION%</td></tr><tr><td>File version</td><td>%ASSEMBLY_VERSION%</td></tr><tr><td>Product version</td><td>%PRODUCT_VERSION%</td></tr><tr><td>Product name</td><td>CIL Browser</td></tr><tr><td>Vendor</td><td>SmallSoft</td></tr></table><p>Copyright (c) 2023, MSDN.WhiteKnight</p>
<table cellpadding=""2px""><tr><td><a href=""assembly.html"">(Assembly manifest)</a></td></tr></table><h2>Namespaces</h2><table cellpadding=""2px""><tr><td><a href=""./CilBrowser.Core/index.html"">CilBrowser.Core</a></td></tr></table>
<hr/><p>Generated by <a href=""https://github.com/MSDN-WhiteKnight/CilBrowser"">CIL Browser</a></p>
</body></html>";

            expected = expected.Replace("%ASSEMBLY_VERSION%", assemblyVersion);
            expected = expected.Replace("%PRODUCT_VERSION%", productVersion);
            expected = expected.Replace("\r\n", "\n").Trim();
            html = html.Replace("\r\n", "\n").Trim();
            Assert.AreEqual(expected, html);
        }
    }
}
